### ISSUE TITLE
custom URL

### ISSUE THREAD

**Issue by aferraz** [hassio-addons/addon-sonweb#2]
## Proposed changes

I want to use a custom url to access sonweb, like https://site.domain.com/sonweb, it this possible ?
In this way I can use the same hassio url.
I tried with Nginx proxy but it fail because on webpage the urls are absolute, for example "/start"

Thank you
 Alessandro

<blockquote><div><strong><a href="https://site.domain.com/sonweb">404 Error - Page Not Found</a></strong></div></blockquote>

**Comment by frenck** [comment]
Hi @aferraz,

You have to setup a reverse proxy for this indeed, like NGinx or Caddy.
Nevertheless, this is kinda out of scope for this add-on.

There are multiple topics on the community forums, you should check it out!

../Frenck
