### ISSUE TITLE
Login page asking for Username/Password

### ISSUE THREAD

**Issue by codenamej6** [hassio-addons/addon-sonweb#4]
I installed this add-on in hass.io following the instructions and embedded it into Home Assistant, but when I click on it or select the "open web ui" button, it shows me a page where I have to put in a username and password to log in.  Can someone help guide me on what to do next, or if I did something wrong and wasn't supposed to see a login page?

**Comment by frenck** [comment]
@codenamej6, this is not a login page, but a register page (the button say "Register", not login.)

**Comment by codenamej6** [comment]
This is what I see, which looks like a login page to me:

![login](https://user-images.githubusercontent.com/37158576/40726211-48153842-63f3-11e8-9d17-0fa2f48d71e5.jpg)
